### ISSUE TITLE
notebook lost after disconnect

### ISSUE THREAD

**Issue by falksticken** [JuliaLang/JuliaBox#199]
How to reproduce:
- open tutorial notebook (e.g. ''Basics")
- open new notebook from tutorial notebook file menu
- rename notebook
- save notebook
- edit something in notebook, save again
- wait until being disconnected
- reconnect

expected:
- notebook can be reopened from tutorial folder

actual:
- notebook cannot be found anywhere under home directory

**Comment by falksticken** [comment]
Was logged in as falk.sticken@gmail.com

**Comment by tanmaykm** [comment]
Thanks for the details.

These steps would create the notebook in the `tutorial` folder. However, the tutorial folder is not backed up, since it can potentially be modified with a new JuliaBox version. This is similar to the Julia packages, `.ipython` folder or any other folder that JuliaBox creates on its own. 

Sub folders of the home folder that are created by the system do not get backed up or may get overwritten. Any other folder/file that you create will be backed up and restored.

For example, the following steps would work as desired:
- `mkdir ~/notebooks`
- `cp ~/tutorial/* ~/notebooks`
- open a notebook from notebooks folder
- ...

**Comment by tanmaykm** [comment]
Closing this as this does not appear to be a bug.

**Comment by ViralBShah** [comment]
Perhaps we should put a note to this effect in the first notebook in the tutorial.

**Comment by tanmaykm** [comment]
Yes.

**Comment by tanmaykm** [comment]
Fixed via https://github.com/JuliaLang/JuliaBox/commit/36f43ffac411608affa42ad49f9d7dcacb73bf94

**Comment by falksticken** [comment]
Thanks for the explanation and quickly providing a user experience
improvement by showing a notification.
