### ISSUE TITLE
Single machine installation failure

### ISSUE THREAD

**Issue by samuelpowell** [JuliaLang/JuliaBox#261]
I am (somewhat blindly) following the new installation instructions for a single machine development set-up and am encountering a small problem.  Step 6 fails with ```ImportError: No module named juliabox.db``` because at this point in the process, the appropriate Python module (which I assume is that located at engine/src) has not be installed on the host.

Is this an oversight in the installation instructions, or am I missing something obvious?

**Comment by tanmaykm** [comment]
Ah yes. That's because the script needs `JuliaBox/engine/src` in `PYTHONPATH`, an oversight in the instructions.

You could make it work by adding it to your env: 
`export PYTHONPATH=${PYTHONPATH}:<path to JuliaBox/engine/src>`

But the right fix will probably be to remove env dependency add the following to `create_tables_sqlite.py` (and a few other such scripts):
````
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "..", "engine", "src"))
````

Will fix it soon, but happy to merge a PR too.
Thanks for pointing it out!
