### ISSUE TITLE
Old packages (?) and lower free space

### ISSUE THREAD

**Issue by z-m-k** [JuliaLang/JuliaBox#285]
Although Interact.jl is currently broken anyway importing it in JuliaBox gives the following:
```Julia
    WARNING: Interact requires IJulia >= v0.1.3 to work properly.
```
Adding IJulia manually removes this warning. Is it possible that precompiled packages are out of date?

Additionally, free space is currently limited to 500MB which I believe was raised earlier in the year. All these issues arose after the last maintenance.

**Comment by tanmaykm** [comment]
@z-m-k thanks for raising this.

Yes, we had increased free space temporarily when JuliaBox default packages were installed into user space. But since #246, that is no longer the case and each user could use around 200MB of additional freed up space. Larger volumes are also possible, but not generally available for cost reasons.

Packages bundled with JuliaBox are currently a snapshot of the day they were built. We do test some of the common packages before releasing, but it is quite possible that some are broken once in a while. And since package update happen once in a 2-4 weeks, they may not be the latest always. Adding your own packages is the way to address such cases. And if the latest package version is still broken, raising an issue with the package repo is the fastest way to get it addressed.

**Comment by tanmaykm** [comment]
Closing as not JuliaBox issue.
