### ISSUE TITLE
Failure to start kernel

### ISSUE THREAD

**Issue by fogeiner** [JuliaLang/JuliaBox#292]
Following the installation instructions I managed to get JuliaBox running in VirtualBox VM environment (the simplest Single-user, Zero-authentication mode with the aim of offline usage).

Unfortunately when I open a notepad I get several error messages:
1. «I couldn't find a kernel matching Julia. Please select a kernel:»
I choose «Julia 0.3.11» and then
2. «The kernel has died, and the automatic restart has failed...»

I tried to launch kernel manually inside the Docker instance using

```root@juliabox:~# cat /home/juser/.ipython/kernels/julia-0.3/kernel.json
{
    "display_name": "Julia 0.3.11", 
    "language": "julia", 
    "argv": [
        "/usr/bin/julia", 
        "-J", 
        "/opt/julia_packages/jimg/stable/sys.ji", 
        "-i", 
        "-F", 
        "/opt/julia_packages/.julia/v0.3/IJulia/src/kernel.jl", 
        "{connection_file}"
    ]
}```

```root@juliabox:~# /usr/bin/julia -J /opt/julia_packages/jimg/stable/sys.ji 
Segmentation fault (core dumped)```

but it is a binary file and I don't clearly see what causes the problem. Is there any way to see the cause of the crash?

**Comment by tanmaykm** [comment]
Looks like precompiling resulted in a corrupted image. You can avoid this by opting out of precompiled image from the JuliaBox settings page.

Otherwise, rebuilding may fix it if there was some temporary issue:
- remove the unbundled packages: `rm -rf /jboxengine/data/packages/julia_packages`
- remove the package bundle: `rm /jboxengine/data/*.tar.gz`
- rebuild: `img_create.sh home /jboxengine/data`

**Comment by fogeiner** [comment]
I confirm that rebuilding does solve the problem in this case. Thank you so much for the quick response!
